# Change "Kaldi" to your site name
title = "ReviByte"
[params]
images = ["img/og-image.jpg"]
description = "ReviByte Technology Reviews delivers honest insights on the latest gadgets, smartphones, apps, and innovations helping you make smarter tech choices"
